// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RehearsalLibrary.Base;

#nullable disable

namespace RehearsalLibrary.Migrations
{
    [DbContext(typeof(RehearshalSqlBase))]
    [Migration("20230417164618_5")]
    partial class _5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RehearsalLibrary.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudioClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudioClientId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.GroupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryStatus")
                        .HasColumnType("int");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<int>("RehearsalHourCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("GroupEntries");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.IndividualEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryStatus")
                        .HasColumnType("int");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<int>("RehearsalHourCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("IndividualEntries");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.VocalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntryStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryStatus")
                        .HasColumnType("int");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<int>("RehearsalHourCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("VocalEntries");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.StudioClient", b =>
                {
                    b.HasBaseType("RehearsalLibrary.Entities.Client");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("StudioClient");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.StudioGuest", b =>
                {
                    b.HasBaseType("RehearsalLibrary.Entities.Client");

                    b.HasDiscriminator().HasValue("StudioGuest");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.Comment", b =>
                {
                    b.HasOne("RehearsalLibrary.Entities.Client", "StudioClient")
                        .WithMany("Comments")
                        .HasForeignKey("StudioClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudioClient");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.GroupEntry", b =>
                {
                    b.HasOne("RehearsalLibrary.Entities.Client", "Client")
                        .WithMany("GroupEntries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.IndividualEntry", b =>
                {
                    b.HasOne("RehearsalLibrary.Entities.Client", "Client")
                        .WithMany("IndividualEntries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.VocalEntry", b =>
                {
                    b.HasOne("RehearsalLibrary.Entities.Client", "Client")
                        .WithMany("VocalEntries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RehearsalLibrary.Entities.Client", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GroupEntries");

                    b.Navigation("IndividualEntries");

                    b.Navigation("VocalEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
